### PR TITLE
Add hero image and fix current month not being set

### LINKED ISSUE #40: FEAT: add image to home component

### PR DESCRIPTION
**Pull request by vitor-afonso**
### PR description

- Adds hero image
- Fix `currentMonth` in Current Month page not being set to the last month in userMonths array when the current month(August) is not open
- Other minor updates 

Screenshot 2023-08-12 at 22 33 26

### CODE REVIEW

File: src/components/Hero.tsx [hunk 1]
```diff
@@ -1,21 +1,52 @@
...
   return (
     <section className='w-full md:w-80'>
-      {!user && (
+      {(!user || (user && userMonths.length < 1)) && (
         <>
-          <div className='w-full md:w-80 h-80 bg-slate-400 mb-4'></div>
-          <Button clickHandler={() => router.push(APP.pageRoutes.login)}>{APP.buttonAction.seeMonths}</Button>
+          {(!user || userIsLoggedInAndCurrentMonthIsNotOpen) && (
+            <div className='w-full md:w-80 h-80 mb-4'>
+              <Image src='/images/budget-transparent-medium.png' width={320} height={320} alt='Colorful machine managing the money' priority />
```
Comment (zandrastr) [inline src/components/Hero.tsx]: Maybe you could put the img path in app.constants file or create a component if you are going to reuse the same img.

**Review by zandrastr — APPROVED** [review]
